### ISSUE TITLE
How to access Temperature data from this chip?

### ISSUE THREAD

**Issue by VinceKezel** [pololu/lsm6-arduino#4]
I see it in the datasheets and am trying to modify the code to get a temp reading from this chip.

I'm doing something that might not be correct... using imu.readReg(0x20) to get the first bit, which seems to come though as decimal. Second bit is imu.readReg(0x21) and is 0 at room temp.
So I do this: `( ( bit1 + ( 255 * bit2 ) ) / 16 ) + 25`

**Comment by kevin-pololu** [comment]
According to the datasheet, "L and H registers together express a 16-bit word in two’s
complement", so you need to interpret the combined value as a signed 16-bit integer. You should also consider avoiding that integer division by 16 so that you don't lose some resolution in the reading. Something like this should work:

```cpp
  uint8_t tl = imu.readReg(0x20);
  uint8_t th = imu.readReg(0x21);
  int16_t raw = (int16_t)(th << 8 | tl);
  float temp = (float)raw / 16 + 25;
```

If you continue to have trouble or have any other questions, please post on [the Pololu Forum](https://forum.pololu.com/) (the GitHub issues are intended to track development of and problems with the library itself).
